<?php


namespace core\user\controllers;


use core\user\models\Model;


class DeleteController extends BaseUser
{


    protected function inputData()
    {

        if(!$this->userId) $this->execBase();

        if(!isset($this->parameters['id'])){
            exit('не указан id');
        }

        $this->createTableData();




    }

    protected function outputData()
    {
        //return parent::outputData(); // TODO: Change the autogenerated stub


        if($_SERVER['REQUEST_METHOD'] == 'DELETE'){

            $this->model->delete($this->table, [
                'where' => [
                    'id' => $this->parameters['id'],
                ]
            ]);

            return 'OK';

        }else{
            echo 'Ошибка';
        }


    }

}